<%@ Language=VBScript %>
<%Option Explicit%>
<!-- #INCLUDE VIRTUAL="/siw/Constants.inc" -->
<!-- #INCLUDE VIRTUAL="/siw/DB_Geral.asp" -->
<!-- #INCLUDE VIRTUAL="/siw/DB_Cliente.asp" -->
<!-- #INCLUDE VIRTUAL="/siw/DB_Seguranca.asp" -->
<!-- #INCLUDE VIRTUAL="/siw/DB_Link.asp" -->
<!-- #INCLUDE VIRTUAL="/siw/DB_EO.asp" -->
<!-- #INCLUDE VIRTUAL="/siw/jScript.asp" -->
<!-- #INCLUDE VIRTUAL="/siw/Funcoes.asp" -->
<%
Response.Expires = -1500
REM =========================================================================
REM  /Default.asp
REM ------------------------------------------------------------------------
REM Nome     : Alexandre Vinhadelli Papadópolis
REM Descricao: Gerencia o portal de currículos
REM Mail     : alex@sbpi.com.br
REM Criacao  : 17/11/2004 14:27
REM Versao   : 1.0.0.0
REM Local    : Brasília - DF
REM -------------------------------------------------------------------------
REM

Dim p_LogOn, p_dbms, p_cliente, p_portal

p_LogOn    = "Sim"
p_dbms     = 1
p_cliente  = 362
p_portal   = "Sim"
Session("dbms") = p_dbms

ShowHTML "<HTML>"
ShowHTML "<HEAD>"
ShowHTML "<TITLE>PORTAL DE CURRÍCULOS DO MS :: </TITLE>"
ShowHTML "<META HTTP-EQUIV=""Content-Type"" CONTENT=""text/html; charset=iso-8859-1"">"
ShowHTML "<SCRIPT language=javascript src=""javas/hoje.js""></SCRIPT>"
ShowHTML "<style>"
ShowHTML "	a:link{color:""#FFFFFF"";text-decoration:none}"
ShowHTML "	a:visited{color:""#FFFFFF"";text-decoration:none}"
ShowHTML "	a:hover{color:""#25687E"";text-decoration:none}"
ShowHTML "</style>"
ShowHTML "<base target=""principal"">"
ShowHTML "</HEAD>"
ShowHTML "<BODY BGCOLOR=#FFFFFF leftmargin=""0"" topmargin=""5"" link=""#FFFFFF"" vlink=""#FFFFFF"" alink=""#FFFFFF"">"
ShowHTML ""
ShowHTML "  <div align=""center"">"
ShowHTML "    <center>"
ShowHTML "    <table border=""0"" width=""98%"" cellspacing=""0"" cellpadding=""0"" height=""100%"">"
ShowHTML "      <tr>"
ShowHTML "        <td width=""100%"" bgcolor=""#FFCC00"" height=""21""><img border=""0"" src=""images/barra_governo_esq_nova.gif"" align=""left"" vspace=""2"" width=""430"" height=""21""><img border=""0"" src=""images/barra_governo_direita_nova.gif"" align=""right"" hspace=""19"" vspace=""2"" width=""74"" height=""21""></td>"
ShowHTML "      </tr>"
ShowHTML "      <tr>"
ShowHTML "        <td width=""100%"" height=""10""></td>"
ShowHTML "      </tr>"
ShowHTML "      <tr>"
ShowHTML "        <td width=""100%"" height=""62"">"
ShowHTML "          <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"">"
ShowHTML "            <tr>"
ShowHTML "              <td width=""187"" height=""62""><img border=""0"" src=""images/topo_foto.jpg"" width=""187"" height=""62""></td>"
ShowHTML "              <td width=""1"" height=""62""><img border=""0"" src=""images/topo_bg.jpg"" width=""1"" height=""62""></td>"
ShowHTML "            </center>"
ShowHTML "              <td width=""100%"" background=""images/topo_bg.jpg"" height=""62"">"
ShowHTML "                <p align=""left""><b><font face=""Verdana"" color=""#FFFFFF"" size=""4"">Portal de currículos do MS</font></b></p>"
ShowHTML "            </td>"
ShowHTML "            <td width=""14"" height=""62"">"
ShowHTML "              <p align=""right""><img border=""0"" src=""images/topo_borda.jpg"" width=""14"" height=""62""></td>"
ShowHTML "          </tr>"
ShowHTML "        </table>"
ShowHTML "      </td>"
ShowHTML "    </tr>"
ShowHTML "    <center>"
ShowHTML "    <tr>"
ShowHTML "      <td width=""100%"" height=""20"">"
ShowHTML "        <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"">"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" background=""images/borda_fora.jpg"" height=""20"">&nbsp;</td>"
ShowHTML "            <td height=""20"">"
ShowHTML "              <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"" bgcolor=""#FFFFFF"" height=""20"">"
ShowHTML "                <tr>"
ShowHTML "                  <td height=""22"" width=""140"" bgcolor=""#FFFFFF"">&nbsp;</td>"
ShowHTML "                  <td height=""22"" align=""center"">"
ShowHTML "                    <div align=""center"">"
ShowHTML "                      <table border=""0"" cellspacing=""0"" cellpadding=""0"" width=""100%"">"
ShowHTML "                        <tr>"
ShowHTML "                          <td width=""8""><img border=""0"" src=""images/menu_e.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                          <td bgcolor=""#3591B3"">"
ShowHTML "                            <p align=""center""><font face=""Verdana"" size=""1"" color=""#FFFFFF""><b><a href=""home.htm"">HOME</a></b></font></p>"
ShowHTML "                          </td>"
ShowHTML "                          <td><img border=""0"" src=""images/menu_d.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                        </tr>"
ShowHTML "                      </table>"
ShowHTML "                    </div>"
ShowHTML "                  </td>"
ShowHTML "                  <td height=""22"" align=""center"">"
ShowHTML "                    <div align=""center"">"
ShowHTML "                      <table border=""0"" cellspacing=""0"" cellpadding=""0"" width=""100%"">"
ShowHTML "                        <tr>"
ShowHTML "                          <td width=""8""><img border=""0"" src=""images/menu_e.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                          <td bgcolor=""#3591B3"">"
ShowHTML "                            <p align=""center""><font face=""Verdana"" size=""1"" color=""#FFFFFF""><b><a href=""oque.htm"">O"
ShowHTML "                            QUE É</a></b></font></td>"
ShowHTML "                          <td><img border=""0"" src=""images/menu_d.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                        </tr>"
ShowHTML "                      </table>"
ShowHTML "                    </div>"
ShowHTML "                  </td>"
ShowHTML "                  <td height=""22"" align=""center"">"
ShowHTML "                    <div align=""center"">"
ShowHTML "                      <table border=""0"" cellspacing=""0"" cellpadding=""0"" width=""100%"">"
ShowHTML "                        <tr>"
ShowHTML "                          <td width=""8""><img border=""0"" src=""images/menu_e.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                          <td bgcolor=""#3591B3"">"
ShowHTML "                            <p align=""center""><font face=""Verdana"" size=""1"" color=""#FFFFFF""><b><a href=""/siw/mod_rh_pub/cv.asp?par=Identificacao&sg=cvident&p_portal=" & p_portal & "&p_LogOn=Sim&p_dbms=" & p_dbms & "&p_cliente=" & p_cliente & "&w_usuario=0"">CADASTRE-SE</a></b></font></td>"
ShowHTML "                          <td><img border=""0"" src=""images/menu_d.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                        </tr>"
ShowHTML "                      </table>"
ShowHTML "                    </div>"
ShowHTML "                  </td>"
ShowHTML "                  <td height=""22"" align=""center"">"
ShowHTML "                    <div align=""center"">"
ShowHTML "                      <table border=""0"" cellspacing=""0"" cellpadding=""0"" width=""100%"">"
ShowHTML "                        <tr>"
ShowHTML "                          <td width=""8""><img border=""0"" src=""images/menu_e.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                          <td bgcolor=""#3591B3"">"
ShowHTML "                            <p align=""center""><font face=""Verdana"" size=""1"" color=""#FFFFFF""><b><a href=""Login.asp?p_portal=" & p_portal & "&p_LogOn=Sim&p_dbms=" & p_dbms & "&p_cliente=" & p_cliente & """>SEU CURRÍCULO</a></b></font></td>"
ShowHTML "                          <td><img border=""0"" src=""images/menu_d.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                        </tr>"
ShowHTML "                      </table>"
ShowHTML "                    </div>"
ShowHTML "                  </td>"
ShowHTML "                </tr>"
ShowHTML "              </table>"
ShowHTML "            </td>"
ShowHTML "            <td width=""19"" background=""images/borda_fora_d.jpg"" height=""22""><img border=""0"" src=""images/borda_fora_d.jpg"" width=""19"" height=""1""></td>"
ShowHTML "          </tr>"
ShowHTML "        </table>"
ShowHTML "      </td>"
ShowHTML "    </tr>"
ShowHTML "    <tr>"
ShowHTML "      <td width=""100%"" height=""5"">"
ShowHTML "        <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"" height=""5"">"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" background=""images/borda_fora.jpg"" height=""5"">&nbsp;</td>"
ShowHTML "            <td height=""5"" bgcolor=""#FFFFFF"">"
ShowHTML "              &nbsp;"
ShowHTML "            </td>"
ShowHTML "            <td width=""19"" background=""images/borda_fora_d.jpg"" height=""5""><img border=""0"" src=""images/borda_fora_d.jpg"" width=""19"" height=""1""></td>"
ShowHTML "          </tr>"
ShowHTML "        </table>"
ShowHTML "      </td>"
ShowHTML "    </tr>"
ShowHTML "    <tr>"
ShowHTML "      <td width=""100%"" height=""22"">"
ShowHTML "        <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"" height=""22"">"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" height=""22"" background=""images/borda_fora.jpg"">&nbsp;</td>"
ShowHTML "            <td height=""22"">"
ShowHTML "              <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"">"
ShowHTML "                <tr>"
ShowHTML "                  <td width=""40""></td>"
ShowHTML "                  <td>"
ShowHTML "                    <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"">"
ShowHTML "                      <tr>"
ShowHTML "                        <td width=""8""><img border=""0"" src=""images/borda_data_e.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                        <td bgcolor=""#3591B3"">"
ShowHTML "              <p align=""center""><font size=""1"" face=""Verdana"" color=""#ffffff"">"
ShowHTML "		<p align=""center""><SCRIPT>DiaDeHoje()</SCRIPT></p>"
ShowHTML "                        </td>"
ShowHTML "                        <td width=""8""><img border=""0"" src=""images/borda_data_d.jpg"" width=""8"" height=""22""></td>"
ShowHTML "                      </tr>"
ShowHTML "                    </table>"
ShowHTML "                  </td>"
ShowHTML "                  <td width=""450""></td>"
ShowHTML "                </tr>"
ShowHTML "              </table>"
ShowHTML "            </td>"
ShowHTML "            <td background=""images/borda_fora_d.jpg"" width=""19"" height=""22"">&nbsp;</td>"
ShowHTML "          </tr>"
ShowHTML "        </table>"
ShowHTML "      </td>"
ShowHTML "    </tr>"
ShowHTML "    <tr>"
ShowHTML "      <td width=""100%"">"
ShowHTML "        <table border=""0"" width=""100%"" cellspacing=""0"" cellpadding=""0"" height=""100%"">"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" height=""15"" background=""images/borda_fora.jpg""><img border=""0"" src=""images/15h.gif"" width=""1"" height=""15""></td>"
ShowHTML "            <td width=""18"" height=""15"" valign=""top""><img border=""0"" src=""images/dentro_canto_sup_e.jpg"" width=""18"" height=""15""></td>"
ShowHTML "            <td height=""15"" background=""images/dentro_topo.jpg""><img border=""0"" src=""images/dentro_topo.jpg"" width=""2"" height=""15""></td>"
ShowHTML "            <td height=""15"" background=""images/dentro_topo.jpg""><img border=""0"" src=""images/dentro_topo.jpg"" width=""2"" height=""15""></td>"
ShowHTML "            <td height=""15"" background=""images/dentro_topo.jpg""><img border=""0"" src=""images/dentro_topo.jpg"" width=""2"" height=""15""></td>"
ShowHTML "            <td height=""15"" width=""18"" valign=""top""><img border=""0"" src=""images/dentro_canto_sup_d.jpg"" width=""18"" height=""15""></td>"
ShowHTML "            <td width=""19"" height=""15"" background=""images/borda_fora_d.jpg""><img border=""0"" src=""images/15h.gif"" width=""1"" height=""15""></td>"
ShowHTML "          </tr>"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" background=""images/borda_fora.jpg"" height=""100%"">&nbsp;</td>"
ShowHTML "            <td width=""18"" background=""images/dentro_borda_e.jpg"" height=""100%"">&nbsp;</td>"
ShowHTML "            <td colspan=""3"" height=""100%""><div style=""OVERFLOW: auto; Z-INDEX: -300""> "
ShowHTML "       <p align=""center""> "
ShowHTML "       <iframe src=""home.htm"" width=""100%"" height=""100%"" border=""0"" leftMargin=""0"" topMargin=""0"" marginheight=""0"" marginwidth=""0"" frameborder=""0"" framespacing=""0"" name=""principal"" noresize oncontextmenu=""return false"" allowtransparency> "
ShowHTML "       </p></iframe></td>"
ShowHTML "            <td width=""18"" background=""images/dentro_borda_d.jpg"" height=""100%"">&nbsp;</td>"
ShowHTML "            <td width=""19"" background=""images/borda_fora_d.jpg"" height=""100%"">&nbsp;</td>"
ShowHTML "          </tr>"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" background=""images/borda_fora.jpg"" height=""17"">&nbsp;</td>"
ShowHTML "            <td width=""18"" valign=""top"" height=""17""><img border=""0"" src=""images/dentro_canto_inf_e.jpg"" width=""18"" height=""17""></td>"
ShowHTML "            <td colspan=""3"" background=""images/dentro_fundo.jpg"" height=""17"">&nbsp;</td>"
ShowHTML "            <td width=""18"" valign=""top"" height=""17""><img border=""0"" src=""images/dentro_canto_inf_d.jpg"" width=""18"" height=""17""></td>"
ShowHTML "            <td width=""19"" background=""images/borda_fora_d.jpg"" height=""17"">&nbsp;</td>"
ShowHTML "          </tr>"
ShowHTML "          <tr>"
ShowHTML "            <td width=""21"" height=""23""><img border=""0"" src=""images/canto_inf_e.jpg"" width=""21"" height=""23""></td>"
ShowHTML "            <td width=""18"" background=""images/borda_fora_fundo.jpg"" height=""23"">&nbsp;</td>"
ShowHTML "            <td background=""images/borda_fora_fundo.jpg"" height=""23""></td>"
ShowHTML "            <td background=""images/borda_fora_fundo.jpg"" height=""23""></td>"
ShowHTML "            <td background=""images/borda_fora_fundo.jpg"" height=""23""></td>"
ShowHTML "            <td width=""18"" background=""images/borda_fora_fundo.jpg"" height=""23""></td>"
ShowHTML "            <td width=""19"" height=""23""><img border=""0"" src=""images/canto_inf_d.jpg"" width=""19"" height=""23""></td>"
ShowHTML "          </tr>"
ShowHTML "        </table>"
ShowHTML "      </td>"
ShowHTML "    </tr>"
ShowHTML "    </table>"
ShowHTML "    </center>"
ShowHTML "  </div>"
ShowHTML "</BODY>"
ShowHTML "</HTML>"

Set p_LogOn   = Nothing
Set p_dbms    = Nothing
Set p_cliente = Nothing
Set p_portal  = Nothing
%>
