\i acesso_lc.sql
\i CalculaIDCC.sql
\i CalculaIGCC.sql
--\i CARREGA_PAC.sql
\i CL_Cadastrador_Geral.sql
\i CL_CriaParametro.sql
\i dados_ferias.sql
\i fvalor.sql
\i GeraCodigoInterno.sql
\i geracpfespecial.sql
\i GetCodigo.sql
\i horario2minutos.sql
\i minutos2horario.sql
\i MontaNomeAlmoxLocal.sql
\i MontaNomeArquivoLocal.sql
\i MontaNomeMenu.sql
\i MontaNomePrestacaoContas.sql
\i MontaNomeSolic.sql
\i MontaNomeTipoAcordo.sql
\i MontaNomeTipoLancamento.sql
\i MontaNomeTipoMaterial.sql
\i MontaNomeTipoRecurso.sql
\i MontaOrdemMenu.sql
\i MontaOrdemUnidade.sql
\i PD_Cadastrador_Geral.sql
\i recuperaValorDiaria.sql
--\i reinicializa_sequences.sql
\i Responsavel_Unidade.sql
\i retornaAfericaoIndicador.sql
\i RetornaBancoHoras.sql
\i retornaExcedenteContrato.sql
\i RetornaLimiteCaixa.sql
\i RetornaLimiteProtocolo.sql
\i sg_geramenu.sql
\i sg_geramenuseg.sql
\i sp_ajustaFasePagamento.sql
\i sp_calculaDiarias.sql
\i sp_geraContrato.sql
\i sp_get10percentdays.sql
\i sp_getAcordoFornecimento.sql
\i SP_GetAlmoxarifado.sql
\i SP_GetArquivo_PA.sql
\i SP_GetCaixa.sql
\i sp_getCategoriaDiaria.sql
\i SP_GetCLFinanceiro.sql
\i sp_getctespecordem.sql
\i SP_GetDescontoAgencia.sql
\i SP_GetGpAlteracaoSalario.sql
\i SP_GetGpDesempenho.sql
\i sp_getGPFamiliares.sql
\i SP_GetGPFerias.sql
\i sp_getGPFeriasDias.sql
\i sp_getGPFolhaPontoDiario.sql
\i sp_getGPFolhaPontoMensal.sql
\i SP_GetGPModalidade.sql
\i SP_getGPPensionista.sql
\i sp_getimpostoincid.sql
\i sp_getIndicador_Aferidor.sql
\i sp_getindice.sql
\i sp_getindicecols.sql
\i sp_getindicetabs.sql
\i sp_getknowarea.sql
\i sp_getlancamento.sql
\i sp_getlancamentodoc.sql
\i sp_getlancamentoitem.sql
\i sp_getlancamentolog.sql
\i sp_getlancamentoprojeto.sql
\i sp_getlancamentorubrica.sql
\i sp_getlcanexo.sql
\i sp_getlccriterio.sql
\i sp_getlcfinalidade.sql
\i sp_getlcfonte.sql
\i sp_getlcfonterecurso.sql
\i sp_getlcjulgamento.sql
\i sp_getlcmodalidade.sql
\i sp_getlcModEnq.sql
\i sp_getlcportalcont.sql
\i sp_getlcportalcontitem.sql
\i sp_getlcportallic.sql
\i sp_getlcportallicitem.sql
\i sp_getlcsituacao.sql
\i sp_getlcunidade.sql
\i sp_getlcunidadefornec.sql
\i sp_getMatImp.sql
\i sp_getMatServ.sql
\i sp_getMeioTransporte.sql
\i sp_getmenuformapag.sql
\i sp_getmenurelac.sql
\i sp_getmenuupper.sql
\i sp_getmenuuser.sql
\i SP_GetMetaAnexo.sql
\i sp_getmodmaster.sql
\i sp_getMoeda.sql
\i SP_GetMtSituacao.sql
\i sp_getnaturezadoc_pa.sql
\i sp_getnatureza_pe.sql
\i sp_getNotaAcordoCancel.sql
\i sp_getobjetivo_pe.sql
\i SP_GetOpiniao.sql
\i sp_getorimport.sql
\i sp_getorprioridade.sql
\i sp_getorprioridadelist.sql
\i sp_getPAElimItem.sql
\i sp_getPAEmpItem.sql
\i SP_GetParametro.sql
\i sp_getPDImportacao.sql
\i SP_GetPDParametro.sql
\i SP_GetPD_Alteracao.sql
\i SP_GetPD_Bilhete.sql
\i SP_GetPD_Deslocamento.sql
\i SP_GetPD_Fatura.sql
\i SP_GetPD_Financeiro.sql
\i SP_GetPD_Reembolso.sql
\i SP_GetPD_Vinculacao.sql
\i sp_getpessoatel.sql
\i sp_getplanoestrategico.sql
\i sp_getPrestacaoContas.sql
\i sp_getprocedure.sql
\i sp_getprocsp.sql
\i sp_getproctabela.sql
\i sp_getproctabs.sql
\i sp_getPrograma.sql
\i sp_getProtocolo.sql
\i sp_getRecurso.sql
\i sp_getRecurso_Disp.sql
\i sp_getRecurso_Indisp.sql
\i sp_getrelaccols.sql
\i sp_getrelacionamento.sql
\i sp_getrelbolsista.sql
\i sp_getrelprogresso.sql
\i sp_getRestricaoEtapa.sql
\i sp_getsistema.sql
\i SP_GetSIWCoordenada.sql
\i sp_getsolicanexo.sql
\i sp_getsolicapoiolist.sql
\i sp_getsolicareas.sql
\i sp_getsoliccl.sql
\i sp_getsolicemail.sql
\i sp_getsolicetapa.sql
\i sp_getsolicetprec.sql
\i sp_getSolicEV.sql
\i SP_GetSolicGP.sql
\i sp_getsolicgr.sql
\i sp_getsolicgra.sql
\i sp_getsolicgri.sql
\i sp_getSolicIndicador.sql
\i sp_getsolicinter.sql
\i sp_getsoliclog.sql
\i sp_getSolicMeta.sql
\i sp_getSolicObjetivo.sql
\i sp_getsolicpa.sql
\i sp_getsolicrecurso.sql
\i sp_getSolicRecursos.sql
\i sp_getsolicrelanexo.sql
\i sp_getsolicresp.sql
\i sp_getSolicRestricao.sql
\i SP_GetSolicResultado.sql
\i sp_getsolicrubrica.sql
\i sp_getSolicSR.sql
\i sp_getsolicviagem.sql
\i sp_getSolic_Vinculo.sql
\i sp_getspparametro.sql
\i sp_getspsp.sql
\i sp_getsptabs.sql
\i sp_getstoredprocedure.sql
\i sp_gettabela.sql
\i sp_gettipoapoiolist.sql
\i sp_getTipoArquivo.sql
\i sp_gettipodado.sql
\i sp_gettipodemanda.sql
\i sp_gettipodespacho_pa.sql
\i sp_gettipodocumento.sql
\i sp_getTipoEvento.sql
\i sp_gettipoguarda_pa.sql
\i sp_getTipoIndicador.sql
\i sp_gettipoindice.sql
\i sp_getTipoInteressado.sql
\i sp_gettipolancamento.sql
\i sp_getTipoLog.sql
\i sp_getTipoMatServ.sql
\i SP_GetTipoMovimentacao.sql
\i sp_gettipopostolist.sql
\i sp_getTipoRecurso.sql
\i sp_getTipoRestricao.sql
\i sp_gettiposp.sql
\i sp_gettipotabela.sql
\i sp_getTipoVeiculo.sql
\i sp_gettramitedata.sql
\i SP_GetTramiteResp.sql
\i SP_GetTramiteSolic.sql
\i sp_gettramiteuser.sql
\i sp_gettrigevento.sql
\i sp_gettrigeventos.sql
\i sp_gettrigger.sql
\i sp_getttprefixo.sql
\i sp_getttramal.sql
\i sp_getttramalusuarioativo.sql
\i sp_getttusuario.sql
\i sp_getUnidadeMedida.sql
\i sp_getunidade_cl.sql
\i sp_getunidade_pa.sql
\i sp_getUnidade_PE.sql
\i sp_getunitpailist.sql
\i sp_getunittypedata.sql
\i sp_getunittypelist.sql
\i sp_getUorgAnexo.sql
\i sp_getuorgresp.sql
\i SP_GetUserResp.sql
\i sp_getusuario.sql
\i sp_getusuariotabs.sql
\i SP_GetUsuarioTemp.sql
\i SP_GetValorDiaria.sql
\i sp_getVeiculo.sql
\i sp_getviagembenef.sql
\i sp_putacaoppa.sql
\i sp_putacordoaditivo.sql
\i sp_putacordoconc.sql
\i sp_putacordodadosadicionais.sql
\i sp_putacordoenvio.sql
\i sp_putAcordoFornecimento.sql
\i sp_putacordogeral.sql
\i sp_putacordonota.sql
\i sp_putacordonotacancel.sql
\i sp_putacordooutra.sql
\i sp_putacordoparc.sql
\i sp_putacordopreposto.sql
\i sp_putacordorep.sql
\i sp_putacordotermo.sql
\i SP_PutACParametro.sql
\i SP_PutAfastamento.sql
\i sp_putagreetype.sql
\i SP_PutAlmoxarifado.sql
\i SP_PutAlmoxarifadoLocal.sql
\i sp_putAnotacao.sql
\i sp_putarquivo.sql
\i SP_PutArquivoLocal_PA.sql
\i SP_PutArquivo_PA.sql
\i sp_putArquivo_PE.sql
\i sp_putassunto_pa.sql
\i sp_putatualizaetapa.sql
\i sp_putbaseline.sql
\i SP_PutCaixa.sql
\i sp_putCaixaDevolucao.sql
\i sp_putCaixaEnvio.sql
\i sp_putcall.sql
\i sp_putcargo.sql
\i SP_PutCategoriaDiaria.sql
\i SP_PutCiaTrans.sql
\i sp_putCLARPItem.sql
\i sp_putcldados.sql
\i SP_PutCLGeral.sql
\i sp_putclitemfornecedor.sql
\i sp_putCLParametro.sql
\i sp_putclpesqfornecedor.sql
\i sp_putclsolicitem.sql
\i SP_PutCLUsuario.sql
\i SP_PutCodigoExterno.sql
\i sp_putcoluna.sql
\i SP_PutCoMoeda.sql
\i sp_putConfCL.sql
\i sp_putConfPD.sql
\i SP_PutConfPJ.sql
\i sp_putcontascronograma.sql
\i sp_putContasRegistro.sql
\i sp_putConvDadosBancario.sql
\i sp_putConvOutraParte.sql
\i sp_putConvOutroRep.sql
\i sp_putConvPreposto.sql
\i sp_putcopesconban.sql
\i sp_putcopestel.sql
\i sp_putCronMeta.sql
\i sp_putCronograma.sql
\i sp_putctespecificacao.sql
\i sp_putcvcargo.sql
\i sp_putcvcurso.sql
\i sp_putcvescola.sql
\i sp_putcvexp.sql
\i sp_putcvhist.sql
\i sp_putcvident.sql
\i sp_putcvidioma.sql
\i sp_putcvproducao.sql
\i SP_PutDataEspecial.sql
\i SP_PutDcOcorrencia.sql
\i sp_putdemandaareas.sql
\i sp_putdemandaconc.sql
\i sp_putdemandaenvio.sql
\i sp_putdemandageral.sql
\i sp_putdemandainter.sql
\i SP_PutDescontoAgencia.sql
\i sp_putdicionario.sql
\i sp_putDocumentoAnexa.sql
\i sp_putDocumentoArqCen.sql
\i sp_putDocumentoArqSet.sql
\i sp_putDocumentoAssunto.sql
\i sp_putDocumentoAutua.sql
\i sp_putDocumentoCaixa.sql
\i sp_putDocumentoDesm.sql
\i sp_putDocumentoEnvio.sql
\i sp_putDocumentoGeral.sql
\i sp_putDocumentoInter.sql
\i sp_putDocumentoJunta.sql
\i sp_putDocumentoReceb.sql
\i sp_puteoaatuac.sql
\i sp_puteolocal.sql
\i sp_puteoresp.sql
\i sp_puteotipoposto.sql
\i sp_puteotipouni.sql
\i sp_puteounidade.sql
\i sp_putespeciedocumento_pa.sql
\i sp_putesquema.sql
\i sp_putesquemaatributo.sql
\i SP_PutEsquemaInsert.sql
\i sp_putesquemascript.sql
\i sp_putesquematabela.sql
\i sp_putetapaarquivo.sql
\i SP_PutEtapaComentario.sql
\i sp_putetapamensal.sql
\i sp_putEtapaProject.sql
\i sp_puteventotrigger.sql
\i sp_putfinanceiroconc.sql
\i sp_putfinanceirogeral.sql
\i SP_PutFNParametro.sql
\i sp_putFormaPagamento.sql
\i sp_putFormaPagamentoVinc.sql
\i sp_putGpAlteracaoSalario.sql
\i SP_PutGPColaborador.sql
\i SP_PutGPContrato.sql
\i sp_putGpDesempenho.sql
\i sp_putGPFamiliares.sql
\i sp_putGpFerias.sql
\i sp_putGPFeriasDias.sql
\i SP_PutGPModalidade.sql
\i SP_PutGPParametro.sql
\i SP_PutGPPensionista.sql
\i sp_putGpPontoDiario.sql
\i sp_putGpPontoMensal.sql
\i SP_PutGPTipoAfast.sql
\i sp_putgrupoveiculo.sql
\i sp_puthorizonte_pe.sql
\i sp_putimposto.sql
\i sp_putIndicador.sql
\i sp_putIndicador_Afericao.sql
\i sp_putIndicador_Aferidor.sql
\i sp_putIndicador_Meta.sql
\i sp_putindice.sql
\i sp_putlancamentodoc.sql
\i sp_putlancamentoenvio.sql
\i sp_putlancamentoitem.sql
\i sp_putlancamentorubrica.sql
\i sp_putlcarquivo.sql
\i sp_putlccriterio.sql
\i sp_putlcdadosanalise.sql
\i sp_putlcEnqMod.sql
\i sp_putlcfinalidade.sql
\i sp_putlcfonte.sql
\i sp_putlcfonterecurso.sql
\i sp_putLCJulgamento.sql
\i sp_putlcmodalidade.sql
\i sp_putlcportalcont.sql
\i sp_putlcportalcontitem.sql
\i sp_putlcportallic.sql
\i sp_putlcportallicitem.sql
\i sp_putlcsituacao.sql
\i sp_putlcunidade.sql
\i sp_putlcunidadefornec.sql
\i sp_putMaterial.sql
\i sp_putMatServ.sql
\i sp_putmenurelac.sql
\i SP_PutMetaAnexo.sql
\i SP_PutMtSituacao.sql
\i sp_putnaturezadoc_pa.sql
\i sp_putnatureza_pe.sql
\i sp_putobjetivo_pe.sql
\i sp_putopiniao.sql
\i sp_putorimport.sql
\i sp_putorprioridade.sql
\i SP_PutPAElimGeral.sql
\i SP_PutPAElimItem.sql
\i SP_PutPAEmpGeral.sql
\i SP_PutPAEmpItem.sql
\i SP_PutPAParametro.sql
\i SP_PutPdDiaria.sql
\i SP_PutPDImportacao.sql
\i SP_PutPdMissao.sql
\i SP_PutPDParametro.sql
\i SP_PutPdTarefa.sql
\i SP_PutPDUnidade.sql
\i sp_putPDUnidLimite.sql
\i SP_PutPDUsuario.sql
\i SP_PutPD_Alteracao.sql
\i SP_PutPD_Atividade.sql
\i SP_PutPD_Bilhete.sql
\i SP_PutPD_Contas.sql
\i SP_PutPD_Cotacao.sql
\i SP_PutPD_Dados.sql
\i SP_PutPD_Deslocamento.sql
\i SP_PutPD_Fatura.sql
\i SP_PutPD_Fatura_Outros.sql
\i SP_PutPD_FimSemana.sql
\i SP_PutPD_Reembolso.sql
\i SP_PutPD_ReembValor.sql
\i sp_putPessoa.sql
\i sp_putPlanoEstrategico.sql
\i sp_putPlano_Menu.sql
\i sp_putPrestacaoContas.sql
\i sp_putprocedure.sql
\i sp_putProgramaConc.sql
\i sp_putProgramaDescritivo.sql
\i sp_putProgramaEnvio.sql
\i sp_putProgramaGeral.sql
\i sp_putProgramaQualit.sql
\i sp_putprojetoacaoppa.sql
\i SP_PutProjetoAnalise.sql
\i sp_putprojetoareas.sql
\i sp_putprojetoconc.sql
\i SP_PutProjetoDescritivo.sql
\i sp_putprojetoenvio.sql
\i sp_putprojetoetapa.sql
\i sp_putprojetofinancacao.sql
\i sp_putprojetogeral.sql
\i sp_putprojetoinfo.sql
\i sp_putprojetointer.sql
\i sp_putprojetooutras.sql
\i sp_putprojetorec.sql
\i sp_putprojetorubrica.sql
\i sp_putramalusuario.sql
\i sp_putRecurso.sql
\i sp_putRecurso_Disp.sql
\i sp_putRecurso_Indisp.sql
\i sp_putRecurso_Menu.sql
\i sp_putrelacionamento.sql
\i sp_putRenumeraProtocolo.sql
\i sp_putrespacao.sql
\i sp_putRestricaoEtapa.sql
\i sp_putRestricaoEtapaInter.sql
\i sp_putsgpermen.sql
\i sp_putsgpesmen.sql
\i sp_putsgtrapes.sql
\i sp_putsistema.sql
\i sp_putsiwcliente.sql
\i sp_putsiwclimod.sql
\i sp_putsiwcoordenada.sql
\i sp_putsiwmenend.sql
\i sp_putsiwpessoamail.sql
\i sp_putsiwtramite.sql
\i sp_putsiwtramitefluxo.sql
\i sp_putsolicarquivo.sql
\i SP_PutSolicConc.sql
\i SP_PutSolicConcTransp.sql
\i SP_PutSolicEnvio.sql
\i sp_putsolicetprec.sql
\i SP_PutSolicEvento.sql
\i SP_PutSolicGeral.sql
\i sp_putSolicIndicador.sql
\i SP_PutSolicInfGeral.sql
\i SP_PutSolicInfTransp.sql
\i sp_putsolicinter.sql
\i sp_putSolicRecAlocacao.sql
\i sp_putSolicRecurso.sql
\i SP_PutSolicRelAnexo.sql
\i sp_putSolicRestricao.sql
\i SP_PutSolicTransp.sql
\i sp_putSolic_Vinculo.sql
\i sp_putspparametro.sql
\i sp_putspsp.sql
\i sp_putsptabs.sql
\i sp_putstoredprocedure.sql
\i sp_puttabela.sql
\i sp_putTipoArquivo.sql
\i sp_puttipodado.sql
\i sp_puttipodemanda.sql
\i sp_puttipodespacho_pa.sql
\i sp_puttipodocumento.sql
\i sp_putTipoEvento.sql
\i sp_puttipoguarda_pa.sql
\i sp_putTipoIndicador.sql
\i sp_puttipoindice.sql
\i sp_putTipoInteressado.sql
\i sp_puttipolancamento.sql
\i sp_putTipoMatServ.sql
\i SP_putTipoMovimentacao.sql
\i sp_putTipoRecurso.sql
\i sp_putTipoRestricao.sql
\i sp_puttiposp.sql
\i sp_puttipotabela.sql
\i sp_puttipoveiculo.sql
\i sp_puttrigevento.sql
\i sp_puttrigger.sql
\i sp_putttcentral.sql
\i sp_putttclassificacao.sql
\i sp_putttprefixo.sql
\i sp_putttramal.sql
\i sp_putttramalusuario.sql
\i sp_puttttronco.sql
\i sp_putUorgArquivo.sql
\i SP_PutUsuarioTemp.sql
\i SP_PutValorDiaria.sql
\i sp_putviagembenef.sql
/*
\i tg_ac_acordo_aditivo_in_up.sql
\i tg_ac_acordo_in_up.sql
\i tg_co_pessoa_in_up.sql
\i TG_FN_DOCUMENTO_ITEM.sql
\i tg_fn_documento_item_in_up.sql
\i tg_fn_lancamento_doc_ex.sql
\i tg_fn_lancamento_doc_in_up.sql
\i TG_FN_LANCAMENTO_IN_UP.sql
\i TG_FN_LANCAMENTO_RUBRICA.sql
\i TG_GP_AFASTAMENTO.sql
\i TG_GP_CONTRATO_COLAB_IN_UP.sql
\i TG_GP_FERIAS_IN_UP.sql
\i TG_PA_ASUNTO_IN_UP.sql
\i TG_PA_DOCUMENTO_IN_UP.sql
\i TG_PA_DOCUMENTO_LOG_IN_UP.sql
\i TG_PD_MISSAO_UP.sql
\i TG_PE_RECURSO_DISP_EX.sql
\i TG_PE_RECURSO_DISP_UP.sql
\i TG_PE_RECURSO_UP.sql
\i TG_SG_AUTENTICACAO_IN_UP.sql
\i tg_siw_restricao_in_up.sql
\i TG_SIW_SOLIC_IN.sql
\i TG_SIW_SOLIC_UP.sql
\i TG_SR_VEICULO_IN_UP.sql
\i triggereventos.sql
\i tt_localidade.sql
*/
