\i to_char.sql
\i to_number.sql
\i trunc.sql
\i instr.sql
\i nvl.sql

\i SP_fGetCcList.sql
\i SP_fGetEtapaList.sql
\i SP_fGetMenuList.sql
\i SP_fGetUorgList.sql

\i acentos.sql
\i Acesso.sql
\i acesso_recurso.sql
\i VerificaDataMovel.sql
\i MontaOrdem.sql
\i pd_retornatrechos.sql

\i criptografia.sql
\i dados_solic.sql
\i Gestor.sql
\i Marcado.sql

\i CalculaIDC.sql
\i CalculaIDE.sql
\i CalculaIGC.sql
\i CalculaIGE.sql
\i SolicRestricao.sql
\i SP_GetAddressData.sql
\i SP_GetAddressList.sql
\i SP_GetAdressTPData.sql
\i SP_GetAdressTPList.sql
\i SP_GetAfastamento.sql
\i SP_GetAlerta.sql
\i SP_GetBankAccList.sql
\i SP_GetBankData.sql
\i SP_GetBankHousData.sql
\i SP_GetBankHousList.sql
\i SP_GetBankList.sql
\i SP_GetBenef.sql
\i SP_GetCCData.sql
\i SP_GetCCSubordinat.sql
\i SP_GetCCTree.sql
\i SP_GetCCTreeVision.sql
\i SP_GetCityData.sql
\i SP_GetCityList.sql
\i SP_GetCompanyData.sql
\i SP_GetCountryData.sql
\i SP_GetCountryList.sql
\i SP_GetCustomerData.sql
\i SP_GetCustomerSite.sql
\i SP_GetDataEspecial.sql
\i SP_GetDefData.sql
\i SP_GetDefGrpData.sql
\i SP_GetDeficGrpList.sql
\i SP_GetDefList.sql
\i SP_GetDeskTop.sql
\i sp_getDesktop_Recurso.sql
\i SP_GetDeskTop_TT.sql
\i SP_GetEtniaData.sql
\i SP_GetEtniaList.sql
\i SP_GetFoneData.sql
\i SP_GetFoneList.sql
\i SP_GetFoneTypeData.sql
\i SP_GetFoneTypeList.sql
\i SP_GetFormatData.sql
\i SP_GetFormatList.sql
\i SP_GetIdiomData.sql
\i SP_GetIdiomList.sql
\i sp_getIndicador.sql
\i SP_GetKindPersList.sql
\i SP_GetLinkData.sql
\i SP_GetLinkDataHelp.sql
\i SP_GetLinkDataUser.sql
\i SP_GetLinkSubMenu.sql
\i SP_GetLnkDataPrnt.sql
\i SP_GetLocalList.sql
\i SP_GetMenuCode.sql
\i SP_GetMenuData.sql
\i sp_getMenuLink.sql
\i SP_GetMenuList.sql
\i SP_GetMenuOrder.sql
\i SP_GetModData.sql
\i SP_GetModList.sql
\i SP_GetPersonData.sql
\i SP_GetPersonList.sql
\i SP_GetRegionData.sql
\i SP_GetRegionList.sql
\i SP_GetSegData.sql
\i SP_GetSegList.sql
\i SP_GetSegModData.sql
\i SP_GetSegModList.sql
\i SP_GetSegName.sql
\i SP_GetSegVincData.sql
\i SP_GetSiwArquivo.sql
\i SP_GetSiwCliData.sql
\i SP_GetSiwCliList.sql
\i SP_GetSiwCliModLis.sql
\i SP_GetSolicList.sql
\i SP_GetStateData.sql
\i SP_GetStateList.sql
\i SP_GetTramiteList.sql
\i SP_GetUorgData.sql
\i SP_GetUorgList.sql
\i SP_GetUserData.sql
\i SP_GetUserList.sql
\i SP_GetUserModule.sql
\i SP_GetUserTypeData.sql
\i SP_GetUserTypeList.sql
\i SP_GetUserVision.sql
\i SP_GetVincKindData.sql
\i SP_GetVincKindList.sql
\i SP_PutCOAgencia.sql
\i SP_PutCOBanco.sql
\i SP_PutCOCidade.sql
\i SP_PutCOEtnia.sql
\i SP_PutCOForm.sql
\i SP_PutCOGRDEF.sql
\i SP_PutCOIdioma.sql
\i SP_PutCOPais.sql
\i SP_PutCoPesEnd.sql
\i SP_PutCORegiao.sql
\i SP_PutCOSegmento.sql
\i SP_PutCoTipoVinc.sql
\i SP_PutCOTPDEF.sql
\i SP_PutCOTPENDER.sql
\i SP_PutCOTPFONE.sql
\i SP_PutCOTPPESSOA.sql
\i SP_PutCOUF.sql
\i SP_PutCTCC.sql
\i SP_PutDMSegVinc.sql
\i SP_PutSgPesMod.sql
\i SP_PutSIWCliConf.sql
\i SP_PutSIWMenu.sql
\i SP_PutSIWModSeg.sql
\i SP_PutSIWModulo.sql
\i SP_PutSiwPesCC.sql
\i SP_PutSiwUsuario.sql
\i SP_UpdatePassword.sql
\i SP_VerificaAssinat.sql
\i SP_VerificaSenha.sql
\i sp_verificausuario.sql
