\i acentos.sql
\i Acesso.sql
\i acesso_recurso.sql
\i ac_criaparametro.sql
\i CalculaIDC.sql
\i CalculaIDE.sql
\i CalculaIGC.sql
\i CalculaIGE.sql
\i criptografia.sql
\i dados_solic.sql
\i fn_criaparametro.sql
\i Gestor.sql
\i instr.sql
\i LimpaOrcamento.sql
\i Marcado.sql
\i MontaOrdem.sql
\i nvl.sql
\i PA_CriaParametro.sql
\i PD_CriaParametro.sql
\i pd_retornatrechos.sql
\i SG_GeraCliMod.sql
\i SolicRestricao.sql
\i sp_ajustaDataEtapa.sql
\i sp_ajustaPesoEtapa.sql
\i sp_ajustaPesquisaMaterial.sql
\i sp_calculaPercEtapa.sql
\i sp_fGetCcList.sql
\i sp_fGetEtapaList.sql
\i sp_fGetMenuList.sql
\i sp_fGetUorgList.sql
\i sp_getAbastecimento.sql
\i sp_getAcaoPPA.sql
\i sp_getAcordoAditivo.sql
\i sp_getAcordoNota.sql
\i sp_getAcordoNotaCancel.sql
\i sp_getAcordoParcela.sql
\i sp_getAcordoRep.sql
\i sp_getACParametro.sql
\i sp_getAddressData.sql
\i sp_getAddressList.sql
\i sp_getAddressMenu.sql
\i sp_getAdressTPData.sql
\i sp_getAdressTPList.sql
\i sp_getAfastamento.sql
\i sp_getAgreeType.sql
\i sp_getAlerta.sql
\i sp_getArquivo.sql
\i sp_getAssunto_PA.sql
\i sp_getBankAccData.sql
\i sp_getBankAccList.sql
\i sp_getBankData.sql
\i sp_getBankHousData.sql
\i sp_getBankHousList.sql
\i sp_getBankList.sql
\i sp_getBenef.sql
\i sp_getCall.sql
\i sp_getCargo.sql
\i sp_getCCData.sql
\i sp_getCCList.sql
\i sp_getCCSubordinat.sql
\i sp_getCCTree.sql
\i sp_getCCTreeVision.sql
\i sp_getCentralTel.sql
\i sp_getCiaTrans.sql
\i sp_getCityData.sql
\i sp_getCityList.sql
\i sp_getCivStateList.sql
\i sp_getCLParametro.sql
\i sp_getCLSolicItem.sql
\i sp_getCodigo.sql
\i sp_getColuna.sql
\i sp_getColunaColuna.sql
\i sp_getCompanyData.sql
\i sp_getContasCronograma.sql
\i sp_getContasRegistro.sql
\i sp_getConvOutraParte.sql
\i sp_getConvOutroRep.sql
\i sp_getConvPreposto.sql
\i sp_getCountryData.sql
\i sp_getCountryList.sql
\i sp_getCronograma.sql
\i sp_getCTEspecificacao.sql
\i sp_getCTEspecificacaoTree.sql
\i sp_getCustomerData.sql
\i sp_getCustomerSite.sql
\i sp_getCV.sql
\i sp_getCVAcadForm.sql
\i sp_getCVIdioma.sql
\i sp_getCVList.sql
\i sp_getCV_Pessoa.sql
\i sp_getDataEspecial.sql
\i sp_getDefData.sql
\i sp_getDefGrpData.sql
\i sp_getDeficGrpList.sql
\i sp_getDefList.sql
\i sp_getDeskTop.sql
\i sp_getDesktop_Recurso.sql
\i sp_getDeskTop_TT.sql
\i sp_getDocumentoAssunto.sql
\i sp_getDocumentoInter.sql
\i sp_getEOAAtuac.sql
\i sp_getEOAAtuacData.sql
\i sp_getEspecieDocumento_PA.sql
\i sp_getEspecOrdem.sql
\i sp_getEsquema.sql
\i sp_getEsquemaAtributo.sql
\i sp_getEsquemaInsert.sql
\i sp_getEsquemaScript.sql
\i sp_getEsquemaTabela.sql
\i sp_getEtapaAnexo.sql
\i sp_getEtapaComentario.sql
\i sp_getEtapaMensal.sql
\i sp_getEtapaOrder.sql
\i sp_getEtniaData.sql
\i sp_getEtniaList.sql
\i sp_getEtpDataPrnt.sql
\i sp_getEtpDataPrnts.sql
\i sp_getEventoTrigger.sql
\i sp_getFeriado.sql
\i sp_getFinacAcaoPPA.sql
\i sp_getFNParametro.sql
\i sp_getFoneData.sql
\i sp_getFoneList.sql
\i sp_getFoneTypeData.sql
\i sp_getFoneTypeList.sql
\i sp_getFormaPagamento.sql
\i sp_getFormatData.sql
\i sp_getFormatList.sql
\i sp_getGPColaborador.sql
\i sp_getGPContrato.sql
\i sp_getGPParametro.sql
\i sp_getGPTipoAfast.sql
\i sp_getGrupoVeiculo.sql
\i sp_getHorizonte_PE.sql
\i sp_getIdiomData.sql
\i sp_getIdiomList.sql
\i sp_getImposto.sql
\i sp_getImpostoDoc.sql
\i sp_getIndicador.sql
\i sp_getKindPersList.sql
\i sp_getLinkData.sql
\i sp_getLinkDataHelp.sql
\i sp_getLinkDataUser.sql
\i sp_getLinkSubMenu.sql
\i sp_getLnkDataPrnt.sql
\i sp_getLnkDataPrnts.sql
\i sp_getLocalList.sql
\i sp_getMenuCode.sql
\i sp_getMenuData.sql
\i sp_getMenuLink.sql
\i sp_getMenuList.sql
\i sp_getMenuOrder.sql
\i sp_getModData.sql
\i sp_getModList.sql
\i sp_getPersonData.sql
\i sp_getPersonList.sql
\i sp_getRegionData.sql
\i sp_getRegionList.sql
\i sp_getSegData.sql
\i sp_getSegList.sql
\i sp_getSegModData.sql
\i sp_getSegModList.sql
\i sp_getSegName.sql
\i sp_getSegVincData.sql
\i sp_getSiwArquivo.sql
\i sp_getSiwCliData.sql
\i sp_getSiwCliList.sql
\i sp_getSiwCliModLis.sql
\i sp_getsolicdata.sql
\i sp_getSolicList.sql
\i sp_getStateData.sql
\i sp_getStateList.sql
\i sp_getTramiteList.sql
\i sp_getUorgData.sql
\i sp_getUorgList.sql
\i sp_getUserData.sql
\i sp_getUserList.sql
\i sp_getUserModule.sql
\i sp_getUserTypeData.sql
\i sp_getUserTypeList.sql
\i sp_getUserVision.sql
\i sp_getVincKindData.sql
\i sp_getVincKindList.sql
\i sp_putCOAgencia.sql
\i sp_putCOBanco.sql
\i sp_putCOCidade.sql
\i sp_putCOEtnia.sql
\i sp_putCOForm.sql
\i sp_putCOGRDEF.sql
\i sp_putCOIdioma.sql
\i sp_putCOPais.sql
\i sp_putCoPesEnd.sql
\i sp_putCORegiao.sql
\i sp_putCOSegmento.sql
\i sp_putCoTipoVinc.sql
\i sp_putCOTPDEF.sql
\i sp_putCOTPENDER.sql
\i sp_putCOTPFONE.sql
\i sp_putCOTPPESSOA.sql
\i sp_putCOUF.sql
\i sp_putCTCC.sql
\i sp_putDMSegVinc.sql
\i sp_putSgPesMod.sql
\i sp_putSIWCliConf.sql
\i sp_putSIWMenu.sql
\i sp_putSIWModSeg.sql
\i sp_putSIWModulo.sql
\i sp_putSiwPesCC.sql
\i sp_putSiwUsuario.sql
\i sp_putSolicApoio.sql
\i sp_putTTUsuarioCentral.sql
\i sp_putUnidadeMedida.sql
\i sp_putUnidade_CL.sql
\i sp_putUnidade_PA.sql
\i sp_putUnidade_PE.sql
\i sp_putUsuario.sql
\i sp_putVeiculo.sql
\i sp_putViagemEnvio.sql
\i sp_putViagemGeral.sql
\i sp_putViagemOutra.sql
\i SP_UpdatePassword.sql
\i SP_VerificaAssinat.sql
\i SP_VerificaSenha.sql
\i sp_verificausuario.sql
\i to_char.sql
\i to_number.sql
\i trunc.sql
\i tt_carregaligacao.sql
\i ValidaCNPJCPF.sql
\i VerificaDataMovel.sql
