create or replace FUNCTION LIMPA_BASE(p_cliente varchar) RETURNS VOID AS $$
DECLARE
  w_cliente numeric(18);
BEGIN
  select a.sq_pessoa into w_cliente from co_pessoa a join siw_cliente b on (a.sq_pessoa = b.sq_pessoa) where a.nome_resumido_ind = upper(p_cliente);
  
  DELETE FROM lignate;
  DELETE FROM ligori;
  DELETE FROM ligrec;
  DELETE FROM tt_ligacao_log;
  DELETE FROM tt_ligacao;
  DELETE FROM tt_ramal_usuario;
  DELETE FROM tt_usuario;
  DELETE FROM tt_ramal;
  DELETE FROM tt_tronco;
  DELETE FROM tt_cc;
  DELETE FROM tt_central;
  DELETE FROM tt_prefixos;
  DELETE FROM or_acao_prioridade;
  DELETE FROM or_acoes;
  DELETE FROM or_acao_financ;
  DELETE FROM or_acao;
  DELETE FROM or_importacao;
  DELETE FROM or_prioridade;
  DELETE FROM pd_diaria;
  DELETE FROM pd_deslocamento;
  DELETE FROM pd_missao_solic;
  DELETE FROM pd_missao;
  DELETE FROM pd_unidade_limite;
  DELETE FROM pd_unidade;
  DELETE FROM pd_usuario;
  DELETE FROM pd_viagem;
  DELETE FROM pd_cia_transporte;
  DELETE FROM gd_demanda_log_arq;
  DELETE FROM gd_demanda_log;
  DELETE FROM gd_demanda_interes;
  DELETE FROM gd_demanda_envolv;
  DELETE FROM gd_demanda;
  DELETE FROM pj_etapa_demanda;
  DELETE FROM pj_etapa_mensal;
  DELETE FROM pj_recurso_etapa;
  DELETE FROM pj_etapa_contrato;
  DELETE FROM pj_projeto_etapa;
  DELETE FROM pj_projeto_envolv;
  DELETE FROM pj_projeto_representante;
  DELETE FROM pj_projeto_interes;
  DELETE FROM pj_projeto_recurso;
  DELETE FROM siw_solic_apoio;
  DELETE FROM siw_solic_log_arq;
  DELETE FROM pj_projeto_log_arq;
  DELETE FROM pj_projeto_log;
  DELETE FROM fn_lancamento_rubrica;
  DELETE FROM fn_documento_item;
  DELETE FROM pj_rubrica;
  DELETE FROM pj_projeto;
  DELETE FROM fn_imposto_doc;
  DELETE FROM fn_imposto_incid;
  DELETE FROM fn_imposto;
  DELETE FROM fn_lancamento_log_arq;
  DELETE FROM fn_lancamento_log;
  DELETE FROM fn_lancamento_doc;
  DELETE FROM fn_lancamento;
  DELETE FROM fn_parametro;
  DELETE FROM fn_tipo_documento;
  DELETE FROM fn_tipo_lancamento;
  DELETE FROM ac_acordo_log_arq;
  DELETE FROM ac_acordo_log;
  DELETE FROM ac_acordo_parcela;
  DELETE FROM ac_acordo_outra_rep;
  DELETE FROM ac_acordo_representante;
  DELETE FROM ac_acordo_preposto;
  DELETE FROM ac_acordo_outra_parte;
  DELETE FROM ac_acordo;
  DELETE FROM ac_parametro;
  DELETE FROM ac_tipo_acordo;
  DELETE FROM pe_programa_log_arq;
  DELETE FROM pe_programa_log;
  DELETE FROM pe_programa;
  DELETE FROM pa_documento_log;
  DELETE FROM pa_documento_interessado;
  DELETE FROM pa_documento_assunto;
  DELETE FROM pa_arquivo;
  DELETE FROM pa_documento;
  DELETE FROM pa_parametro;
  DELETE FROM pa_especie_documento;
  DELETE FROM pa_assunto;
  DELETE FROM pa_tipo_guarda;
  DELETE FROM pa_natureza_documento;
  DELETE FROM pa_tipo_despacho;
  DELETE FROM pa_unidade;
  DELETE FROM siw_solic_log;
  DELETE FROM lc_arquivo;
  DELETE FROM lc_portal_contrato_item;
  DELETE FROM lc_portal_contrato;
  DELETE FROM lc_portal_lic_item;
  DELETE FROM lc_portal_lic;
  DELETE FROM lc_unidade_fornec;
  DELETE FROM lc_unidade;
  DELETE FROM lc_situacao;
  DELETE FROM lc_modalidade;
  DELETE FROM lc_julgamento;
  DELETE FROM lc_fonte_recurso;
  DELETE FROM lc_finalidade;
  DELETE FROM gp_ferias_aviso;
  DELETE FROM gp_ferias_interrupcao;
  DELETE FROM gp_ferias;
  DELETE FROM gp_afastamento_envio;
  DELETE FROM gp_afastamento_modalidade;
  DELETE FROM gp_afastamento;
  DELETE FROM gp_contrato_colaborador;
  DELETE FROM gp_colaborador;
  DELETE FROM gp_modalidade_contrato;
  DELETE FROM gp_tipo_afastamento;
  DELETE FROM gp_parametro;
  DELETE FROM siw_solic_arquivo;
  DELETE FROM siw_solicitacao_interessado;
  DELETE FROM siw_solic_indicador;
  DELETE FROM siw_solic_meta;
  DELETE FROM siw_solic_recurso_log;
  DELETE FROM siw_solic_recurso_alocacao;
  DELETE FROM siw_solic_recurso;
  DELETE FROM eo_indicador_afericao;
  DELETE FROM eo_indicador_aferidor;
  DELETE FROM eo_indicador_agenda;
  DELETE FROM eo_indicador;
  DELETE FROM eo_recurso_indisponivel;
  DELETE FROM eo_recurso_menu;
  DELETE FROM eo_recurso_disponivel;
  DELETE FROM eo_recurso;
  DELETE FROM pe_plano_menu;
  DELETE FROM pe_plano_arq;
  DELETE FROM siw_solicitacao;
  DELETE FROM pe_objetivo;
  DELETE FROM pe_plano;
  DELETE FROM pe_horizonte;
  DELETE FROM pe_natureza;
  DELETE FROM pe_unidade;
  DELETE FROM siw_solicitacao_interessado;
  DELETE FROM siw_tipo_interessado;
  DELETE FROM siw_tipo_apoio;
  DELETE FROM eo_tipo_recurso;
  DELETE FROM eo_tipo_indicador;

  DELETE FROM sg_perfil_menu a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM sg_pessoa_menu a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM sg_tramite_pessoa a where a.sq_siw_tramite in (select sq_siw_tramite from siw_tramite a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente)));
  DELETE FROM siw_menu_relac a where a.servico_cliente in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM siw_tramite a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM siw_menu_forma_pag a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM siw_menu_endereco a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM siw_menu_arquivo a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM siw_pessoa_cc a where a.sq_menu in (select sq_menu from siw_menu a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM siw_menu a where a.sq_pessoa not in (1,w_cliente);
  
  DELETE FROM sg_autenticacao a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai not in (1,w_cliente));
  DELETE FROM sg_pessoa_modulo a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai not in (1,w_cliente));

  DELETE FROM co_forma_pagamento a where a.cliente in (select sq_pessoa from co_pessoa where sq_pessoa <> w_cliente and sq_pessoa_pai <> w_cliente);
  DELETE FROM co_pessoa_conta a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa <> w_cliente and sq_pessoa_pai <> w_cliente);
  DELETE FROM co_pessoa_endereco a where a.sq_pessoa in (select sq_pessoa from co_pessoa where (sq_pessoa not in (1,w_cliente) and sq_pessoa_pai not in (1,w_cliente)));
  DELETE FROM co_pessoa_telefone a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa <> w_cliente and sq_pessoa_pai <> w_cliente);
  DELETE FROM co_pessoa_fisica a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa <> w_cliente and sq_pessoa_pai <> w_cliente);
  DELETE FROM co_pessoa_juridica a where a.sq_pessoa not in (1,w_cliente) and a.sq_pessoa not in (1,w_cliente);
  DELETE FROM co_pessoa_segmento a where a.sq_pessoa not in (1,w_cliente);

  DELETE FROM cv_pessoa_area a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa_cargo a where a.sq_cvpesexp in (select x.sq_cvpesexp from cv_pessoa_exp x where x.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente));
  DELETE FROM cv_pessoa_curso a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa_escol a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa_exp a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa_hist a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa_idioma a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa_prod a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);
  DELETE FROM cv_pessoa a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai <> w_cliente);

  DELETE FROM eo_unidade_resp a where a.sq_pessoa in (select sq_pessoa from co_pessoa where sq_pessoa_pai not in (1,w_cliente));

  DELETE FROM co_forma_pagamento a where a.cliente in (select sq_pessoa from co_pessoa where sq_pessoa not in (1,w_cliente) and sq_pessoa_pai not in (1,w_cliente));

  DELETE FROM eo_data_especial a where a.cliente not in (1,w_cliente);
  DELETE FROM eo_institucional a where a.sq_unidade in (select sq_unidade from eo_unidade a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM eo_posto_trabalho a where a.cliente not in (1,w_cliente);
  DELETE FROM eo_produto a where a.cliente not in (1,w_cliente);
  DELETE FROM eo_servico a where a.cliente not in (1,w_cliente);
  DELETE FROM eo_tipo_posto a where a.cliente not in (1,w_cliente);
  DELETE FROM eo_localizacao a where a.sq_unidade in (select sq_unidade from eo_unidade a where a.sq_pessoa not in (1,w_cliente));
  DELETE FROM eo_unidade a where a.sq_pessoa not in (1,w_cliente);
  DELETE FROM eo_area_atuacao a where a.sq_pessoa not in (1,w_cliente);
  DELETE FROM eo_tipo_unidade a where a.sq_pessoa not in (1,w_cliente);
  
  DELETE FROM ct_cc a where a.cliente not in (1,w_cliente);
  DELETE FROM siw_cliente_modulo a where a.sq_pessoa not in (1,w_cliente);
  
  DELETE FROM dc_arquivo a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_indice_cols a where a.sq_indice in (select sq_indice from dc_indice z where z.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_esquema_atributo a where a.sq_coluna in (select sq_coluna from dc_coluna z where z.sq_tabela in (select sq_tabela from dc_tabela where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente)));
  DELETE FROM dc_relac_cols a where a.sq_relacionamento in (select sq_relacionamento from dc_relacionamento z where z.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_esquema_insert a where a.sq_esquema_tabela in (select sq_esquema_tabela from dc_esquema_tabela a where a.sq_esquema in (select sq_esquema from dc_esquema x where x.cliente <> w_cliente));
  DELETE FROM dc_coluna a where a.sq_tabela in (select sq_tabela from dc_tabela where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_esquema_tabela a where a.sq_esquema in (select sq_esquema from dc_esquema x where x.cliente <> w_cliente);
  DELETE FROM dc_ocorrencia a where a.sq_esquema in (select sq_esquema from dc_esquema x where x.cliente <> w_cliente);
  DELETE FROM dc_esquema a where a.cliente <> w_cliente;
  DELETE FROM dc_indice a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_proc_param a where a.sq_procedure in (select sq_procedure from dc_procedure where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_proc_sp a where a.sq_procedure in (select sq_procedure from dc_procedure where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_proc_tabela a where a.sq_procedure in (select sq_procedure from dc_procedure where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_procedure a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_relacionamento a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_sp_param a where a.sq_stored_proc in (select sq_stored_proc from dc_stored_proc where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_sp_sp a where a.sp_pai in (select sq_stored_proc from dc_stored_proc where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_sp_tabs a where a.sq_stored_proc in (select sq_stored_proc from dc_stored_proc where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_stored_proc a where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_trigger_evento a where a.sq_trigger in (select sq_trigger from dc_trigger where sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente));
  DELETE FROM dc_trigger a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_tabela a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_usuario a where a.sq_sistema in (select sq_sistema from dc_sistema x where x.cliente <> w_cliente);
  DELETE FROM dc_sistema a where a.cliente <> w_cliente;
  DELETE FROM siw_arquivo;
  update co_pessoa a set a.sq_tipo_vinculo = null where sq_pessoa not in (1,w_cliente) and sq_pessoa_pai not in (1,w_cliente);
  DELETE FROM co_tipo_vinculo a where a.cliente not in (1,w_cliente);
  DELETE FROM siw_cliente a where a.sq_pessoa not in (1,w_cliente);
  DELETE FROM co_pessoa where sq_pessoa not in (1,w_cliente) and sq_pessoa_pai not in (1,w_cliente);
END; $$ LANGUAGE 'PLPGSQL' VOLATILE;