<?php
// =========================================================================
// Rotina de emissão da ordem de serviço
// -------------------------------------------------------------------------
function elim_listagem($l_chave,$l_unidade,$l_sg,$l_formato='0') {
  extract($GLOBALS);
  
  // Recupera os dados da tarefa
  $sql = new db_getLinkData; $RS1 = $sql->getInstanceof($dbms,$w_cliente,$l_sg);
  $sql = new db_GetSolicPA; $RS = $sql->getInstanceOf($dbms,f($RS1,'sq_menu'),$w_usuario,f($RS1,'sigla'),4,
      $p_ini_i,$p_ini_f,$p_fim_i,$p_fim_f,$p_atraso,$p_solicitante,
      $p_unidade,$p_prioridade,$p_ativo,$p_proponente,
      $l_chave, $p_assunto, $p_pais, $p_regiao, $p_uf, $p_cidade, $p_usu_resp,
      $p_uorg_resp, $p_palavra, $p_prazo, $p_fase, $p_sqcc, $p_projeto, $p_atividade, 
      null, null, $p_empenho, $p_servico);
  foreach($RS as $row) { $RS = $row; break; }
  
  $sql = new db_GetSolicPA; $RS_Lista = $sql->getInstanceOf($dbms,f($RS1,'sq_menu'),$w_usuario,'LISTELIM',4,
      $p_ini_i,$p_ini_f,$p_fim_i,$p_fim_f,$p_atraso,$p_solicitante,
      $l_unidade,$p_prioridade,$p_ativo,$p_proponente,
      $l_chave, $p_assunto, $p_pais, $p_regiao, $p_uf, $p_cidade, $p_usu_resp,
      $p_uorg_resp, $p_palavra, $p_prazo, $p_fase, $p_sqcc, $p_projeto, $p_atividade, 
      null, null, $p_empenho, $p_servico);
  $RS_Lista = SortArray($RS_Lista, 'codigo', 'asc');
  
  if (nvl($l_unidade,'')=='') {
    $w_nm_unidade = 'UNIDADE/SETOR';
  } else {
    $sql = new db_getUorgData; $RS_Unidade = $sql->getInstanceOf($dbms,$l_unidade);
    $w_nm_unidade = upper(f($RS_Unidade,'nome'));
  }
  
  $sql = new db_getCustomerData; $RS_Cliente = $sql->getInstanceOf($dbms,$w_cliente);
  $w_nm_cliente = upper(f($RS_Cliente,'nome'));

  $l_html ='<html xmlns:v="urn:schemas-microsoft-com:vml"';
  $l_html.=$crlf.'xmlns:o="urn:schemas-microsoft-com:office:office"';
  $l_html.=$crlf.'xmlns:w="urn:schemas-microsoft-com:office:word"';
  $l_html.=$crlf.'xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"';
  $l_html.=$crlf.'xmlns="http://www.w3.org/TR/REC-html40">';
  $l_html.=$crlf.'<head>';
  $l_html.=$crlf.'<meta http-equiv=Content-Type content="text/html; charset=windows-1252">';
  $l_html.=$crlf.'<meta name=ProgId content=Word.Document>';
  $l_html.=$crlf.'<meta name=Generator content="Microsoft Word 12">';
  $l_html.=$crlf.'<meta name=Originator content="Microsoft Word 12">';
  $l_html.=$crlf.'<link rel=File-List href="doc1_arquivos/filelist.xml">';
  $l_html.=$crlf.'<!--[if gte mso 9]><xml>';
  $l_html.=$crlf.' <o:DocumentProperties>';
  $l_html.=$crlf.'  <o:Author>Alexandre Vinhadelli Papadópolis</o:Author>';
  $l_html.=$crlf.'  <o:LastAuthor>Alexandre Vinhadelli Papadópolis</o:LastAuthor>';
  $l_html.=$crlf.'  <o:Revision>2</o:Revision>';
  $l_html.=$crlf.'  <o:TotalTime>11</o:TotalTime>';
  $l_html.=$crlf.'  <o:Created>2011-11-07T19:00:00Z</o:Created>';
  $l_html.=$crlf.'  <o:LastSaved>2011-11-07T19:00:00Z</o:LastSaved>';
  $l_html.=$crlf.'  <o:Pages>1</o:Pages>';
  $l_html.=$crlf.'  <o:Words>142</o:Words>';
  $l_html.=$crlf.'  <o:Characters>773</o:Characters>';
  $l_html.=$crlf.'  <o:Lines>6</o:Lines>';
  $l_html.=$crlf.'  <o:Paragraphs>1</o:Paragraphs>';
  $l_html.=$crlf.'  <o:CharactersWithSpaces>914</o:CharactersWithSpaces>';
  $l_html.=$crlf.'  <o:Version>12.00</o:Version>';
  $l_html.=$crlf.' </o:DocumentProperties>';
  $l_html.=$crlf.'</xml><![endif]-->';
  $l_html.=$crlf.'<link rel=themeData href="doc1_arquivos/themedata.thmx">';
  $l_html.=$crlf.'<link rel=colorSchemeMapping href="doc1_arquivos/colorschememapping.xml">';
  $l_html.=$crlf.'<!--[if gte mso 9]><xml>';
  $l_html.=$crlf.' <w:WordDocument>';
  $l_html.=$crlf.'  <w:View>Print</w:View>';
  $l_html.=$crlf.'  <w:Zoom>120</w:Zoom>';
  $l_html.=$crlf.'  <w:SpellingState>Clean</w:SpellingState>';
  $l_html.=$crlf.'  <w:GrammarState>Clean</w:GrammarState>';
  $l_html.=$crlf.'  <w:TrackMoves>false</w:TrackMoves>';
  $l_html.=$crlf.'  <w:TrackFormatting/>';
  $l_html.=$crlf.'  <w:HyphenationZone>21</w:HyphenationZone>';
  $l_html.=$crlf.'  <w:PunctuationKerning/>';
  $l_html.=$crlf.'  <w:ValidateAgainstSchemas/>';
  $l_html.=$crlf.'  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>';
  $l_html.=$crlf.'  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>';
  $l_html.=$crlf.'  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>';
  $l_html.=$crlf.'  <w:DoNotPromoteQF/>';
  $l_html.=$crlf.'  <w:LidThemeOther>PT-BR</w:LidThemeOther>';
  $l_html.=$crlf.'  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>';
  $l_html.=$crlf.'  <w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>';
  $l_html.=$crlf.'  <w:Compatibility>';
  $l_html.=$crlf.'   <w:BreakWrappedTables/>';
  $l_html.=$crlf.'   <w:SnapToGridInCell/>';
  $l_html.=$crlf.'   <w:WrapTextWithPunct/>';
  $l_html.=$crlf.'   <w:UseAsianBreakRules/>';
  $l_html.=$crlf.'   <w:DontGrowAutofit/>';
  $l_html.=$crlf.'   <w:SplitPgBreakAndParaMark/>';
  $l_html.=$crlf.'   <w:DontVertAlignCellWithSp/>';
  $l_html.=$crlf.'   <w:DontBreakConstrainedForcedTables/>';
  $l_html.=$crlf.'   <w:DontVertAlignInTxbx/>';
  $l_html.=$crlf.'   <w:Word11KerningPairs/>';
  $l_html.=$crlf.'   <w:CachedColBalance/>';
  $l_html.=$crlf.'  </w:Compatibility>';
  $l_html.=$crlf.'  <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>';
  $l_html.=$crlf.'  <m:mathPr>';
  $l_html.=$crlf.'   <m:mathFont m:val="Cambria Math"/>';
  $l_html.=$crlf.'   <m:brkBin m:val="before"/>';
  $l_html.=$crlf.'   <m:brkBinSub m:val="&#45;-"/>';
  $l_html.=$crlf.'   <m:smallFrac m:val="off"/>';
  $l_html.=$crlf.'   <m:dispDef/>';
  $l_html.=$crlf.'   <m:lMargin m:val="0"/>';
  $l_html.=$crlf.'   <m:rMargin m:val="0"/>';
  $l_html.=$crlf.'   <m:defJc m:val="centerGroup"/>';
  $l_html.=$crlf.'   <m:wrapIndent m:val="1440"/>';
  $l_html.=$crlf.'   <m:intLim m:val="subSup"/>';
  $l_html.=$crlf.'   <m:naryLim m:val="undOvr"/>';
  $l_html.=$crlf.'  </m:mathPr></w:WordDocument>';
  $l_html.=$crlf.'</xml><![endif]--><!--[if gte mso 9]><xml>';
  $l_html.=$crlf.' <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="true"';
  $l_html.=$crlf.'  DefSemiHidden="true" DefQFormat="false" DefPriority="99"';
  $l_html.=$crlf.'  LatentStyleCount="267">';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="0" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Normal"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="heading 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 7"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 8"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 9"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 7"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 8"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" Name="toc 9"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="35" QFormat="true" Name="caption"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="10" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Title"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="1" Name="Default Paragraph Font"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="0" Name="Body Text"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="11" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Subtitle"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="22" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Strong"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="20" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Emphasis"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="59" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Table Grid"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" UnhideWhenUsed="false" Name="Placeholder Text"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="1" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="No Spacing"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" UnhideWhenUsed="false" Name="Revision"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="34" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="List Paragraph"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="29" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Quote"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="30" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Intense Quote"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid Accent 1"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid Accent 2"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid Accent 3"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid Accent 4"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid Accent 5"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="60" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Shading Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="61" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light List Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="62" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Light Grid Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="63" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="64" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="65" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 1 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="66" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium List 2 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="67" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="68" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="69" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="70" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Dark List Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="71" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Shading Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="72" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful List Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="73" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" Name="Colorful Grid Accent 6"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="19" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Subtle Emphasis"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="21" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Intense Emphasis"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="31" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Subtle Reference"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="32" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Intense Reference"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="33" SemiHidden="false"';
  $l_html.=$crlf.'   UnhideWhenUsed="false" QFormat="true" Name="Book Title"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="37" Name="Bibliography"/>';
  $l_html.=$crlf.'  <w:LsdException Locked="false" Priority="39" QFormat="true" Name="TOC Heading"/>';
  $l_html.=$crlf.' </w:LatentStyles>';
  $l_html.=$crlf.'</xml><![endif]-->';
  $l_html.=$crlf.'<style>';
  $l_html.=$crlf.'<!--';
  $l_html.=$crlf.' /* Font Definitions */';
  $l_html.=$crlf.' @font-face';
  $l_html.=$crlf.'  {font-family:"Cambria Math";';
  $l_html.=$crlf.'  panose-1:2 4 5 3 5 4 6 3 2 4;';
  $l_html.=$crlf.'  mso-font-charset:0;';
  $l_html.=$crlf.'  mso-generic-font-family:roman;';
  $l_html.=$crlf.'  mso-font-pitch:variable;';
  $l_html.=$crlf.'  mso-font-signature:-1610611985 1107304683 0 0 159 0;}';
  $l_html.=$crlf.'@font-face';
  $l_html.=$crlf.'  {font-family:"Arial Unicode MS";';
  $l_html.=$crlf.'  panose-1:2 11 6 4 2 2 2 2 2 4;';
  $l_html.=$crlf.'  mso-font-charset:128;';
  $l_html.=$crlf.'  mso-generic-font-family:swiss;';
  $l_html.=$crlf.'  mso-font-pitch:variable;';
  $l_html.=$crlf.'  mso-font-signature:-134238209 -371195905 63 0 4129279 0;}';
  $l_html.=$crlf.'@font-face';
  $l_html.=$crlf.'  {font-family:Calibri;';
  $l_html.=$crlf.'  panose-1:2 15 5 2 2 2 4 3 2 4;';
  $l_html.=$crlf.'  mso-font-charset:0;';
  $l_html.=$crlf.'  mso-generic-font-family:swiss;';
  $l_html.=$crlf.'  mso-font-pitch:variable;';
  $l_html.=$crlf.'  mso-font-signature:-1610611985 1073750139 0 0 159 0;}';
  $l_html.=$crlf.'@font-face';
  $l_html.=$crlf.'  {font-family:"Albertus Medium";';
  $l_html.=$crlf.'  panose-1:0 0 0 0 0 0 0 0 0 0;';
  $l_html.=$crlf.'  mso-font-charset:0;';
  $l_html.=$crlf.'  mso-generic-font-family:swiss;';
  $l_html.=$crlf.'  mso-font-format:other;';
  $l_html.=$crlf.'  mso-font-pitch:variable;';
  $l_html.=$crlf.'  mso-font-signature:3 0 0 0 1 0;}';
  $l_html.=$crlf.'@font-face';
  $l_html.=$crlf.'  {font-family:"\@Arial Unicode MS";';
  $l_html.=$crlf.'  panose-1:2 11 6 4 2 2 2 2 2 4;';
  $l_html.=$crlf.'  mso-font-charset:128;';
  $l_html.=$crlf.'  mso-generic-font-family:swiss;';
  $l_html.=$crlf.'  mso-font-pitch:variable;';
  $l_html.=$crlf.'  mso-font-signature:-134238209 -371195905 63 0 4129279 0;}';
  $l_html.=$crlf.' /* Style Definitions */';
  $l_html.=$crlf.' p.MsoNormal, li.MsoNormal, div.MsoNormal';
  $l_html.=$crlf.'  {mso-style-unhide:no;';
  $l_html.=$crlf.'  mso-style-qformat:yes;';
  $l_html.=$crlf.'  mso-style-parent:"";';
  $l_html.=$crlf.'  margin:0cm;';
  $l_html.=$crlf.'  margin-bottom:.0001pt;';
  $l_html.=$crlf.'  mso-pagination:widow-orphan;';
  $l_html.=$crlf.'  font-size:12.0pt;';
  $l_html.=$crlf.'  font-family:"Times New Roman","serif";';
  $l_html.=$crlf.'  mso-fareast-font-family:"Times New Roman";';
  $l_html.=$crlf.'  mso-fareast-language:EN-GB;}';
  $l_html.=$crlf.'p.MsoBodyText, li.MsoBodyText, div.MsoBodyText';
  $l_html.=$crlf.'  {mso-style-noshow:yes;';
  $l_html.=$crlf.'  mso-style-link:"Corpo de texto Char";';
  $l_html.=$crlf.'  mso-margin-top-alt:auto;';
  $l_html.=$crlf.'  margin-right:0cm;';
  $l_html.=$crlf.'  mso-margin-bottom-alt:auto;';
  $l_html.=$crlf.'  margin-left:0cm;';
  $l_html.=$crlf.'  mso-pagination:widow-orphan;';
  $l_html.=$crlf.'  font-size:12.0pt;';
  $l_html.=$crlf.'  font-family:"Arial Unicode MS","sans-serif";}';
  $l_html.=$crlf.'span.CorpodetextoChar';
  $l_html.=$crlf.'  {mso-style-name:"Corpo de texto Char";';
  $l_html.=$crlf.'  mso-style-noshow:yes;';
  $l_html.=$crlf.'  mso-style-unhide:no;';
  $l_html.=$crlf.'  mso-style-locked:yes;';
  $l_html.=$crlf.'  mso-style-link:"Corpo de texto";';
  $l_html.=$crlf.'  mso-ansi-font-size:12.0pt;';
  $l_html.=$crlf.'  mso-bidi-font-size:12.0pt;';
  $l_html.=$crlf.'  font-family:"Arial Unicode MS","sans-serif";';
  $l_html.=$crlf.'  mso-ascii-font-family:"Arial Unicode MS";';
  $l_html.=$crlf.'  mso-fareast-font-family:"Arial Unicode MS";';
  $l_html.=$crlf.'  mso-hansi-font-family:"Arial Unicode MS";';
  $l_html.=$crlf.'  mso-bidi-font-family:"Arial Unicode MS";';
  $l_html.=$crlf.'  mso-fareast-language:PT-BR;}';
  $l_html.=$crlf.'.MsoChpDefault';
  $l_html.=$crlf.'  {mso-style-type:export-only;';
  $l_html.=$crlf.'  mso-default-props:yes;';
  $l_html.=$crlf.'  font-size:10.0pt;';
  $l_html.=$crlf.'  mso-ansi-font-size:10.0pt;';
  $l_html.=$crlf.'  mso-bidi-font-size:10.0pt;';
  $l_html.=$crlf.'  mso-ascii-font-family:Calibri;';
  $l_html.=$crlf.'  mso-ascii-theme-font:minor-latin;';
  $l_html.=$crlf.'  mso-fareast-font-family:Calibri;';
  $l_html.=$crlf.'  mso-fareast-theme-font:minor-latin;';
  $l_html.=$crlf.'  mso-hansi-font-family:Calibri;';
  $l_html.=$crlf.'  mso-hansi-theme-font:minor-latin;';
  $l_html.=$crlf.'  mso-bidi-font-family:"Times New Roman";';
  $l_html.=$crlf.'  mso-bidi-theme-font:minor-bidi;';
  $l_html.=$crlf.'  mso-fareast-language:EN-US;}';
  $l_html.=$crlf.'@page WordSection1';
  $l_html.=$crlf.'  {size:595.3pt 841.9pt;';
  $l_html.=$crlf.'  margin:70.85pt 35.35pt 70.85pt 3.0cm;';
  $l_html.=$crlf.'  mso-header-margin:35.4pt;';
  $l_html.=$crlf.'  mso-footer-margin:35.4pt;';
  $l_html.=$crlf.'  mso-paper-source:0;}';
  $l_html.=$crlf.'div.WordSection1';
  $l_html.=$crlf.'  {page:WordSection1;}';
  $l_html.=$crlf.'-->';
  $l_html.=$crlf.'</style>';
  $l_html.=$crlf.'<!--[if gte mso 10]>';
  $l_html.=$crlf.'<style>';
  $l_html.=$crlf.' /* Style Definitions */';
  $l_html.=$crlf.' table.MsoNormalTable';
  $l_html.=$crlf.'  {mso-style-name:"Tabela normal";';
  $l_html.=$crlf.'  mso-tstyle-rowband-size:0;';
  $l_html.=$crlf.'  mso-tstyle-colband-size:0;';
  $l_html.=$crlf.'  mso-style-noshow:yes;';
  $l_html.=$crlf.'  mso-style-priority:99;';
  $l_html.=$crlf.'  mso-style-qformat:yes;';
  $l_html.=$crlf.'  mso-style-parent:"";';
  $l_html.=$crlf.'  mso-padding-alt:0cm 5.4pt 0cm 5.4pt;';
  $l_html.=$crlf.'  mso-para-margin:0cm;';
  $l_html.=$crlf.'  mso-para-margin-bottom:.0001pt;';
  $l_html.=$crlf.'  mso-pagination:widow-orphan;';
  $l_html.=$crlf.'  font-size:10.0pt;';
  $l_html.=$crlf.'  font-family:"Calibri","sans-serif";';
  $l_html.=$crlf.'  mso-ascii-font-family:Calibri;';
  $l_html.=$crlf.'  mso-ascii-theme-font:minor-latin;';
  $l_html.=$crlf.'  mso-hansi-font-family:Calibri;';
  $l_html.=$crlf.'  mso-hansi-theme-font:minor-latin;';
  $l_html.=$crlf.'  mso-fareast-language:EN-US;}';
  $l_html.=$crlf.'</style>';
  $l_html.=$crlf.'<![endif]--><!--[if gte mso 9]><xml>';
  $l_html.=$crlf.' <o:shapedefaults v:ext="edit" spidmax="3074"/>';
  $l_html.=$crlf.'</xml><![endif]--><!--[if gte mso 9]><xml>';
  $l_html.=$crlf.' <o:shapelayout v:ext="edit">';
  $l_html.=$crlf.'  <o:idmap v:ext="edit" data="1"/>';
  $l_html.=$crlf.' </o:shapelayout></xml><![endif]-->';
  $l_html.=$crlf.'</head>';
  $l_html.=$crlf.'';
  $l_html.=$crlf.'<body lang=PT-BR style=\'tab-interval:35.4pt\'>';
  $l_html.=$crlf.'';
  $l_html.=$crlf.'<div class=WordSection1>';
  $l_html.=$crlf.'';
  $l_html.=$crlf.'<table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0';
  $l_html.=$crlf.' style=\'margin-left:5.35pt;border-collapse:collapse;border:none;mso-border-alt:';
  $l_html.=$crlf.' solid windowtext .75pt;mso-yfti-tbllook:1184;mso-padding-alt:0cm 5.35pt 0cm 5.35pt;';
  $l_html.=$crlf.' mso-border-insidev:.75pt solid windowtext\'>';
  $l_html.=$crlf.' <tr style=\'mso-yfti-irow:0;mso-yfti-firstrow:yes\'>';
  $l_html.=$crlf.'  <td width=435 colspan=6 valign=top style=\'width:326.05pt;border:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-bottom:none;mso-border-top-alt:solid windowtext .75pt;mso-border-left-alt:';
  $l_html.=$crlf.'  solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-top:0cm;margin-right:5.65pt;margin-bottom:';
  $l_html.=$crlf.'  0cm;margin-left:5.65pt;margin-bottom:.0001pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>LISTAGEM DE ELIMINAÇÃO DE DOCUMENTOS<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-top:0cm;margin-right:5.65pt;margin-bottom:';
  $l_html.=$crlf.'  0cm;margin-left:5.65pt;margin-bottom:.0001pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>'.$w_nm_cliente.'<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-top:0cm;margin-right:5.65pt;margin-bottom:';
  $l_html.=$crlf.'  0cm;margin-left:5.65pt;margin-bottom:.0001pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>'.$w_nm_unidade.'<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=189 colspan=2 valign=top style=\'width:5.0cm;border-top:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-left:none;border-bottom:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-top:0cm;margin-right:-5.35pt;margin-bottom:';
  $l_html.=$crlf.'  0cm;margin-left:2.85pt;margin-bottom:.0001pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>ÓRGÃO/SETOR: ___________<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-top:0cm;margin-right:-5.35pt;margin-bottom:';
  $l_html.=$crlf.'  0cm;margin-left:2.85pt;margin-bottom:.0001pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>LISTAGEM Nº:______________<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-left:2.85pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>FOLHA Nº:__________________<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.' </tr>';
  $l_html.=$crlf.' <tr style=\'mso-yfti-irow:1\'>';
  $l_html.=$crlf.'  <td width=66 rowspan=2 style=\'width:49.65pt;border:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-bottom:none;mso-border-top-alt:solid windowtext .75pt;mso-border-left-alt:';
  $l_html.=$crlf.'  solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:7.5pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>CÓDIGO OU<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>Nº. DO ITEM<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=94 rowspan=2 style=\'width:70.85pt;border-top:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-left:none;border-bottom:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>ASSUNTO<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>SÉRIE<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=95 rowspan=2 style=\'width:70.9pt;border-top:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-left:none;border-bottom:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:-5.35pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>DATAS-LIMITE<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=180 colspan=3 style=\'width:134.65pt;border:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-left:none;mso-border-left-alt:solid windowtext .75pt;mso-border-alt:';
  $l_html.=$crlf.'  solid windowtext .75pt;padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>UNIDADE DE ARQUIVAMENTO<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=189 colspan=2 rowspan=2 style=\'width:5.0cm;border-top:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-left:none;border-bottom:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>OBSERVAÇÕES/JUSTIFICATIVA<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.' </tr>';
  $l_html.=$crlf.' <tr style=\'mso-yfti-irow:2\'>';
  $l_html.=$crlf.'  <td width=66 valign=top style=\'width:49.6pt;border:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-top-alt:solid windowtext .75pt;mso-border-left-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-top-alt:solid windowtext .75pt;mso-border-left-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-right-alt:solid windowtext .75pt;padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
  $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>QUANT.<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=113 colspan=2 valign=top style=\'width:3.0cm;border-top:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-left:none;border-bottom:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
  $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
  $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'>ESPECIFICAÇÃO<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.' </tr>';
  foreach ($RS_Lista as $row) {
    $l_html.=$crlf.' <tr style=\'mso-yfti-irow:3\'>';
    $l_html.=$crlf.'  <td width=66 valign=top style=\'width:49.65pt;border:solid windowtext 1.0pt;';
    $l_html.=$crlf.'  mso-border-alt:solid windowtext .5pt;mso-border-right-alt:solid windowtext .75pt;';
    $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
    $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
    $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>'.f($row,'codigo');
    $l_html.=$crlf.'  <o:p></o:p></span></p></td>';
    $l_html.=$crlf.'  <td width=94 valign=top style=\'width:70.85pt;border:solid windowtext 1.0pt;';
    $l_html.=$crlf.'  border-left:none;mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:';
    $l_html.=$crlf.'  .5pt;mso-border-left-alt:.75pt;mso-border-bottom-alt:.5pt;mso-border-right-alt:';
    $l_html.=$crlf.'  .75pt;mso-border-color-alt:windowtext;mso-border-style-alt:solid;padding:';
    $l_html.=$crlf.'  0cm 5.35pt 0cm 5.35pt\'>';
    $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-right:2.85pt;';
    $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>'.f($row,'descricao');
    $l_html.=$crlf.'  <o:p></o:p></span></p></td>';
    $l_html.=$crlf.'  <td width=95 valign=top style=\'width:70.9pt;border:solid windowtext 1.0pt;';
    $l_html.=$crlf.'  border-left:none;mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:';
    $l_html.=$crlf.'  .5pt;mso-border-left-alt:.75pt;mso-border-bottom-alt:.5pt;mso-border-right-alt:';
    $l_html.=$crlf.'  .75pt;mso-border-color-alt:windowtext;mso-border-style-alt:solid;padding:';
    $l_html.=$crlf.'  0cm 5.35pt 0cm 5.35pt\'>';
    $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
    $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>'.f($row,'datas_limite');
    $l_html.=$crlf.'  <o:p></o:p></span></p></td>';
    $l_html.=$crlf.'  <td width=66 valign=top style=\'width:49.6pt;border:solid windowtext 1.0pt;';
    $l_html.=$crlf.'  border-left:none;mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:';
    $l_html.=$crlf.'  .5pt;mso-border-left-alt:.75pt;mso-border-bottom-alt:.5pt;mso-border-right-alt:';
    $l_html.=$crlf.'  .75pt;mso-border-color-alt:windowtext;mso-border-style-alt:solid;padding:';
    $l_html.=$crlf.'  0cm 5.35pt 0cm 5.35pt\'>';
    $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
    $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>'.f($row,'qtd');
    $l_html.=$crlf.'  <o:p></o:p></span></p></td>';
    $l_html.=$crlf.'  <td width=113 colspan=2 valign=top style=\'width:3.0cm;border:solid windowtext 1.0pt;';
    $l_html.=$crlf.'  border-left:none;mso-border-left-alt:solid windowtext .75pt;mso-border-top-alt:';
    $l_html.=$crlf.'  .5pt;mso-border-left-alt:.75pt;mso-border-bottom-alt:.5pt;mso-border-right-alt:';
    $l_html.=$crlf.'  .75pt;mso-border-color-alt:windowtext;mso-border-style-alt:solid;padding:';
    $l_html.=$crlf.'  0cm 5.35pt 0cm 5.35pt\'>';
    $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-right:2.85pt;';
    $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>'.f($row,'especies');
    $l_html.=$crlf.'  <o:p></o:p></span></p></td>';
    $l_html.=$crlf.'  <td width=189 colspan=2 valign=top style=\'width:5.0cm;border:solid windowtext 1.0pt;';
    $l_html.=$crlf.'  border-left:none;mso-border-left-alt:solid windowtext .75pt;mso-border-alt:';
    $l_html.=$crlf.'  solid windowtext .5pt;mso-border-left-alt:solid windowtext .75pt;padding:';
    $l_html.=$crlf.'  0cm 5.35pt 0cm 5.35pt\'>';
    $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'margin-right:2.85pt;text-align:center;';
    $l_html.=$crlf.'  line-height:9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;';
    $l_html.=$crlf.'  font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
    $l_html.=$crlf.'  </td>';
    $l_html.=$crlf.' </tr>';
  }$l_html.=$crlf.' <tr style=\'mso-yfti-irow:4;page-break-inside:avoid\'>';
  $l_html.=$crlf.'  <td width=161 colspan=2 valign=top style=\'width:120.5pt;border-top:none;';
  $l_html.=$crlf.'  border-left:solid windowtext 1.0pt;border-bottom:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-left-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:6.0pt;font-family:"Albertus Medium","sans-serif"\'>LOCAL/DATA<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>________<span';
  $l_html.=$crlf.'  style=\'mso-spacerun:yes\'>       </span>___/___/__<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>________________________<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
  $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>RESPONSÁVEL';
  $l_html.=$crlf.'  <o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
  $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>PELA';
  $l_html.=$crlf.'  SELEÇÃO<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td nowrap width=95 valign=top style=\'width:70.9pt;border:none;padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:6.0pt;font-family:"Albertus Medium","sans-serif"\'>LOCAL/DATA<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>___/__/__<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=113 colspan=2 valign=top style=\'width:3.0cm;border:none;border-right:';
  $l_html.=$crlf.'  solid windowtext 1.0pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>_______________<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'line-height:9.0pt;mso-line-height-rule:exactly\'><span';
  $l_html.=$crlf.'  style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>PRESIDENTE';
  $l_html.=$crlf.'  DA <o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
  $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>COMISSÃO';
  $l_html.=$crlf.'  <o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
  $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>PERMANENTE';
  $l_html.=$crlf.'  DE AVALIAÇÃO<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td nowrap width=94 colspan=2 valign=top style=\'width:70.85pt;border:none;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:6.0pt;font-family:"Albertus Medium","sans-serif"\'>LOCAL/DATA<br>____________,';
  $l_html.=$crlf.'  <o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>___/___/___<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=161 valign=top style=\'width:120.5pt;border:none;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-right-alt:solid windowtext .75pt;padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:6.0pt;font-family:"Albertus Medium","sans-serif"\'>AUTORIZO:<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'margin-right:-7.85pt;text-align:justify;line-height:';
  $l_html.=$crlf.'  9.0pt;mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:';
  $l_html.=$crlf.'  "Albertus Medium","sans-serif"\'>________________________<o:p></o:p></span></p>';
  $l_html.=$crlf.'  <p class=MsoNormal align=center style=\'text-align:center;line-height:9.0pt;';
  $l_html.=$crlf.'  mso-line-height-rule:exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'>AUTORIDADE';
  $l_html.=$crlf.'  DO ÓRGÃO A QUEM COMPETE AUTORIZAR<o:p></o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.' </tr>';
  $l_html.=$crlf.' <tr style=\'mso-yfti-irow:5;mso-yfti-lastrow:yes;page-break-inside:avoid\'>';
  $l_html.=$crlf.'  <td width=161 colspan=2 valign=top style=\'width:120.5pt;border:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  border-top:none;mso-border-left-alt:solid windowtext .75pt;mso-border-bottom-alt:';
  $l_html.=$crlf.'  solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=95 valign=top style=\'width:70.9pt;border:none;border-bottom:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-bottom-alt:solid windowtext .75pt;padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=113 colspan=2 valign=top style=\'width:3.0cm;border-top:none;';
  $l_html.=$crlf.'  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-bottom-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=94 colspan=2 valign=top style=\'width:70.85pt;border:none;';
  $l_html.=$crlf.'  border-bottom:solid windowtext 1.0pt;mso-border-bottom-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.'  <td width=161 valign=top style=\'width:120.5pt;border-top:none;border-left:';
  $l_html.=$crlf.'  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;';
  $l_html.=$crlf.'  mso-border-bottom-alt:solid windowtext .75pt;mso-border-right-alt:solid windowtext .75pt;';
  $l_html.=$crlf.'  padding:0cm 5.35pt 0cm 5.35pt\'>';
  $l_html.=$crlf.'  <p class=MsoNormal style=\'text-align:justify;line-height:9.0pt;mso-line-height-rule:';
  $l_html.=$crlf.'  exactly\'><span style=\'font-size:8.0pt;font-family:"Albertus Medium","sans-serif"\'><o:p>&nbsp;</o:p></span></p>';
  $l_html.=$crlf.'  </td>';
  $l_html.=$crlf.' </tr>';
  $l_html.=$crlf.' <![if !supportMisalignedColumns]>';
  $l_html.=$crlf.' <tr height=0>';
  $l_html.=$crlf.'  <td width=66 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=116 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=95 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=68 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=54 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=110 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=42 style=\'border:none\'></td>';
  $l_html.=$crlf.'  <td width=161 style=\'border:none\'></td>';
  $l_html.=$crlf.' </tr>';
  $l_html.=$crlf.' <![endif]>';
  $l_html.=$crlf.'</table>';
  $l_html.=$crlf.'<p class=MsoNormal><o:p>&nbsp;</o:p></p>';
  $l_html.=$crlf.'</div>';
  $l_html.=$crlf.'</body>';
  $l_html.=$crlf.'</html>';
  return $l_html;
} 
?>