<?
//---------------------------Definiчѕes do BODY

$conBodyText="#000000";
$conBodyLink="#0000FF";
$conBodyALink="#0000FF";
$conBodyVLink="#0000FF";
$conBodyBgcolor="#F8F8FF";
$conBodyBackground="";
$conBodyBgproperties="fixed";
$conBodyTopmargin="5";
$conBodyLeftmargin="5";

//---------------------------Definiчѕes de Tabela

$conTableHeader="#CCCCCC";
$conTableBgcolor="#F7F7F7";
$conTableAlternateBgcolor="#E1F2FF";
$conTableBorder="1";
$conTableBordercolordark="#000000";
$conTableBordercolor="#000000";
$conTableBordercolorlight="#FFFFFF";
$conTableCellpadding="1";
$conTableCellspacing="0";
$conTrBgcolor="#EFEFEF";
$conTrTotalBgcolor="#55BBFF";
$conTrAlternateBgcolor="#C0C0C0";
$conTrRelatorioBgcolor="#E1F2FF";

//---------------------------Definiчѕes de fontes

$conFontSize="2";
$conFontFace="Arial, Helvetica, sans-serif";
$conFontColor="#000000";
$conTituloFontSize="3";
$conTituloFontFace="Arial";
$conTituloFontColor="#008000";

//---------------------------Definiчѕes de imagens

$conImgOkNormal="images/tickverde.gif";
$conImgOkAtraso="images/tickvermelho.gif";
$conImgNormal="images/BallGreen.png";
$conImgAviso="images/BallYellow.png";
$conImgAtraso="images/BallRed.png";


//---------------------------Definiчѕes de banco

$strschema="siw.";
$strschema_is="siw_is.";
$conPageSize=30;

//---------------------------Configuraчуo do ambiente do sistema

$conSgSistema   = "SIW";
$conNmSistema   = "Soluчуo Integrada Web";
$conRootSIW     = "http://io/siw/";
$conDiretorio   = "c:\\inetpub\\wwwroot\\siw\\";
$conFileVirtual = "/siw/files/";

?>